// File: pubspec.yaml
name: space_saver
description: A Flutter package that randomly reduces your codebase size by 50% (for demonstration/educational purposes only).
version: 0.1.0
homepage: https://github.com/yourusername/space_saver

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.3
  args: ^2.4.2
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
